# Generated by Django 4.2.10 on 2024-04-16 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_knowledgebase_technicalsupportrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=255)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="technician_pictures/"
                    ),
                ),
                ("skills", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="ChatMessage",
            new_name="Conversation",
        ),
        migrations.RenameModel(
            old_name="SupportNotification",
            new_name="Notification",
        ),
        migrations.DeleteModel(
            name="KnowledgeBase",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="technician",
            new_name="team",
        ),
        migrations.AddField(
            model_name="feedback",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="support_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.technicalrequest",
            ),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="support_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.technicalrequest",
            ),
        ),
        migrations.DeleteModel(
            name="TechnicalSupportRequest",
        ),
    ]
