# Generated by Django 4.2.10 on 2024-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_technicalrequest_technician_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
