# Generated by Django 4.2.10 on 2024-05-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("issue_description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="service_requests/"
                    ),
                ),
            ],
        ),
    ]
